# This is a basic workflow to help you get started with Actions

name: Python Environment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Install Python dependencies
        run: |
          python -m pip install matplotlib numpy MeshPy scipy

      - name: Hello World 
        run: |
          python -c "import numpy as np; print('Numpy version: '+np.__version__)"
          python -c "import matplotlib as mpl; print('Matplotlib version: '+mpl.__version__)"
        
      - name: Run code
        run: |
          python FEM_AMR_L_dom.py

      - name: Upload to GitHub repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Commit to Github
          file_pattern: 'Figs/Undeformed and deformed FEA meshes.png'

      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: deformation_plots
          path: Figs/*.png
